### ISSUE TITLE
关于ultimate clash规则的问题

### ISSUE THREAD

**Issue by MuXia-0326** [Colin-XKL/RSSmanX#20]
我现在的需求是需要使用rsshub上的v2ex和pixiv相关的rss源

但是从日志上来看，rsshub匹配到局域网规则，然后走的直连，导致pixiv和v2ex连接不上

不知有解决方案没 orz

clash日志
```bash
time="2024-01-11T15:00:33+08:00" level=info msg="[TCP] 172.18.0.7:43138 --> rsshub:80 match IPCIDR(172.16.0.0/12) using DIRECT"
time="2024-01-11T15:03:55+08:00" level=info msg="[TCP] 172.18.0.7:35512 --> rsshub:80 match IPCIDR(172.16.0.0/12) using DIRECT"
```

rsshub日志
```bash
error: Request https://www.v2ex.com/api/topics/latest.json fail, retry attempt #2: RequestError: Client network socket disconnected before secure TLS connection was established
info: /pixiv/ranking/week, user IP: ::ffff:172.18.0.5
error: Pixiv refresh token failed.
error: undefined
error: Error in /ranking/week: pixiv not login

```

**Comment by Colin-XKL** [comment]
你看的那部分clash日志，意思是ttrss通过clash访问rsshub，由于两个在同一个网络下，所以走的直连，这个是预期内的。你想要的是rsshub连接v2ex这些外部站点的时候走clash的是吧，这个需要先确保给rsshub指定了proxy环境变量，默认是有配置的，可以检查下是否正常。

此外，底下贴的pixiv不能访问的日志，这里日志内容是说让你登录，不登陆无法从pixiv获取内容，你可以参考下rsshub的相关文档配置好token再试下

**Comment by MuXia-0326** [comment]
> 你看的那部分clash日志，意思是ttrss通过clash访问rsshub，由于两个在同一个网络下，所以走的直连，这个是预期内的。你想要的是rsshub连接v2ex这些外部站点的时候走clash的是吧，这个需要先确保给rsshub指定了proxy环境变量，默认是有配置的，可以检查下是否正常。
> 
> 此外，底下贴的pixiv不能访问的日志，这里日志内容是说让你登录，不登陆无法从pixiv获取内容，你可以参考下rsshub的相关文档配置好token再试下

pixiv的token是有配置的，我看docker-compose.yml中也是有给rsshub指定proxy的，所以很纳闷，为啥连接不上

config.yaml
```yaml
# clash config file
# version 1.8
# last update 2022-11-06

# clash config wiki
# https://github.com/Dreamacro/clash/wiki/Configuration

# Port of HTTP(S) proxy server on the local end
port: 8080

# Port of SOCKS5 proxy server on the local end
socks-port: 8085

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS5 server on the same port
# mixed-port: 7890

allow-lan: true
bind-address: '*'
mode: rule

# info / warning / error / debug / silent
log-level: info

ipv6: false

profile:
    store-selected: false

dns:
    enable: false

# proxies:

proxy-providers:
    Subscription1:
        type: http
        url: '自己的节点'
        interval: 3600
        path: ./server/Subscription1.yaml
        health-check:
            enable: true
            url: https://cp.cloudflare.com/generate_204
            interval: 600

    Subscription2:
        type: http
        url: '自己的节点'
        interval: 3600
        path: ./server/Subscription2.yaml
        health-check:
            enable: true
            url: https://cp.cloudflare.com/generate_204
            interval: 600

proxy-groups:
    # url-test select which proxy will be used by benchmarking speed to a URL.
    # fallback selects an available policy by priority. The availability is tested by accessing an URL, just like an auto url-test group.
    - name: 'fq'
      type: fallback
      use:
          - Subscription1
          - Subscription2
      # lazy: true
      url: 'https://www.google.com/robots.txt'
      interval: 100

    - name: 'global-random'
      type: load-balance
      use:
          - Subscription1
          - Subscription2
      proxies:
          - DIRECT
      url: 'http://www.gstatic.com/generate_204'
      interval: 300
      # use round robin to request the url via random proxies
      # or consistent-hashing will request same url via same proxy
      strategy: round-robin

rules:
    # bypass local
    - IP-CIDR,127.0.0.0/8,DIRECT
    - IP-CIDR,172.16.0.0/12,DIRECT
    - IP-CIDR,10.0.0.0/8,DIRECT
    - IP-CIDR,192.168.0.0/16,DIRECT

    # hot blocked site
    - DOMAIN-KEYWORD,google,fq
    - DOMAIN-KEYWORD,wikipedia,fq
    - DOMAIN-KEYWORD,facebook,fq
    - DOMAIN-KEYWORD,intgram,fq
    - DOMAIN-KEYWORD,telegram,fq
    - DOMAIN-KEYWORD,pixiv,fq
    - DOMAIN-KEYWORD,pximg,fq
    - DOMAIN-KEYWORD,v2ex,fq
    - DOMAIN,rsshub.app,fq

    # anti cloudflare
    - IP-CIDR,103.21.244.0/22,global-random
    - IP-CIDR,103.22.200.0/22,global-random
    - IP-CIDR,103.31.4.0/22,global-random
    - IP-CIDR,104.16.0.0/13,global-random
    - IP-CIDR,104.24.0.0/14,global-random
    - IP-CIDR,108.162.192.0/18,global-random
    - IP-CIDR,131.0.72.0/22,global-random
    - IP-CIDR,141.101.64.0/18,global-random
    - IP-CIDR,162.158.0.0/15,global-random
    - IP-CIDR,172.64.0.0/13,global-random
    - IP-CIDR,173.245.48.0/20,global-random
    - IP-CIDR,188.114.96.0/20,global-random
    - IP-CIDR,190.93.240.0/20,global-random
    - IP-CIDR,197.234.240.0/22,global-random
    - IP-CIDR,198.41.128.0/17,global-random

    # anti anti crawler
    - DOMAIN-KEYWORD,wechat,global-random
    - DOMAIN-KEYWORD,wexin,global-random
    - DOMAIN-KEYWORD,douban,global-random
    - DOMAIN,wemp.app,global-random
    - DOMAIN,ershicimi.com,global-random
    - DOMAIN,segmentfault.com,global-random

    # default
    - GEOIP,CN,DIRECT
    - MATCH,global-random
```

docker-compose.yaml rsshub部分
```yaml
service.rsshub:
    image: diygod/rsshub
    container_name: rsshub
    depends_on:
      - service.redis
      - service.clash
    restart: on-failure:5
    # ports:
    #     - '1200:1200'
    environment:
      PORT: 80
      # miscellaneous settings
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: redis://service.redis:6379/
      PUPPETEER_WS_ENDPOINT: ws://service.browserless:3000
      # use proxy
      PROXY_URI: socks5://clash:8085
      REQUEST_RETRY: 5
      PROXY_STRATEGY: on_retry
    env_file:
      - rsshub.env
    expose:
      - 80
    networks:
      - net_public
      - net_private
    dns:
      - 223.5.5.5
      - 8.8.8.8
    volumes:
      - *use-local-time-zone
      - *use-local-time
    labels:
      - com.centurylinklabs.watchtower.enable=true # keep the rsshub up to date
      - one.colinx.rssmanx.description='RSShub makes everything rssable'
```

rsshub.env
```.env
PIXIV_REFRESHTOKEN=xxxxxxxxxx
PIXIV_BYPASS_CDN=true
PIXIV_BYPASS_DOH=https://doh.pub/dns-query
PIXIV_IMG_PROXY=https://i.pixiv.cat
```
