### ISSUE TITLE
ttrss容器启动失败，提示config.php，无法修改

### ISSUE THREAD

**Issue by KingStoning** [Colin-XKL/RSSmanX#24]
亲爱的开发者您好，部署完之后，ttrss容器无法启动，提示**config.php 第七行**错误
`PHP Parse error: syntax error, unexpected identifier "pass_for_DB", expecting ")" in /var/www/config.php on line 7`

在宝塔面板的的文件搜索，搜到修改
![image](https://github.com/user-attachments/assets/b9948f2f-05a3-49ca-93a6-6b054fff8e45)

`putenv('TTRSS_DB_PASS='pass_for_DB'');  `
但是修改之后又会恢复原样，通过ChatGPT询问，需要找到挂载卷但是一个找不到

**Comment by Colin-XKL** [comment]
TTRSS_DB_PASS  这个是个环境变量，用来设置数据库密码的。你是自定义了这个密码，吗还是使用的默认值？如果是自定义密码的话先检查一下有没有使用除了字母和数字之外的特殊字符

**Comment by KingStoning** [comment]
> TTRSS_DB_PASS 这个是个环境变量，用来设置数据库密码的。你是自定义了这个密码，吗还是使用的默认值？如果是自定义密码的话先检查一下有没有使用除了字母和数字之外的特殊字符

谢谢提醒我去看看，感谢

**Comment by KingStoning** [comment]
亲爱的开发者您好，很抱歉又要打扰您了，希望您能在闲时看看，感谢您用您宝贵的时间回复：

按照原来的默认配置没有自定义密码，显示这个起初的错误
配置如下
![image](https://github.com/user-attachments/assets/adf05e82-4707-4af2-ae85-074bbd96ae30)

我去.env文件修改密码为 **12345**后，docker容器**启动成功**，但是**日志显示无法连接数据库**
![image](https://github.com/user-attachments/assets/58cee1da-457c-4336-8b32-10d259bcfefb)
![image](https://github.com/user-attachments/assets/ab97a6ca-020e-4dab-a8ef-b9b85ad49a93)

此配置涉及ttrss的相关代码
```
`x-local-time-zone:
 #  - &use-local-time-zone /etc/timezone:/etc/timezone:ro
  - &use-local-time /etc/localtime:/etc/localtime:ro
x-custom-password: &use-custom-passwd ${DB_Password:-'pass_for_DB'} # please change the password in .env file or here
x-http-proxy: &use-custom-http-proxy clash:8080
x-common-logging: &common-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"  # Maximum log file size (e.g., 10 megabytes)
      max-file: "3"    # Maximum number of log files to keep (e.g., 3 files)`
` app.ttrss:
    image: wangqiru/ttrss
    container_name: ttrss
    depends_on:
      - database.ttrss
      - service.clash
    ports:
      - 8000:80/tcp # change the port if you need
    environment:
      SELF_URL_PATH: ttrss.kingkang.xyz # please change to your own domain
      DISABLE_USER_IN_DAYS: 14
      ALLOW_PORTS: 80,443,3000
      # proxy
      HTTP_PROXY: *use-custom-http-proxy
      # database settings
      DB_HOST: database.ttrss
      DB_PORT: 5432
      DB_NAME: ttrss
      DB_USER: postgres
      DB_PASS: *use-custom-passwd
      ENABLE_PLUGINS: auth_internal,fever # auth_internal is required.
    networks:
      - net_public
      - net_private
    volumes:
 #     - *use-local-time-zone
      - *use-local-time
      - feed-favicon-cache:/var/www/cache/feed-icons
      - starred-image-cache:/var/www/cache/starred-images
      - plugin:/var/www/plugins.local
      - theme:/var/www/themes.local
    labels:
      - one.colinx.rssmanx.description='Tiny Tiny RSS is a free and open source web-based news feed (RSS/Atom) reader and aggregator'
    restart: always
    <<: *common-logging`
```
